# Generated by Django 3.2.25 on 2024-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0002_auto_20240316_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('社会人', '社会人'), ('大学生', '大学生'), ('中学生', '中学生'), ('小学生', '小学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('運動', '運動'), ('PC', 'PC'), ('TV', 'TV'), ('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('映画', '映画'), ('読書', '読書')], max_length=8),
        ),
    ]
