# Generated by Django 3.2.25 on 2024-03-19 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0003_auto_20240316_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roots',
            name='rooter',
        ),
        migrations.AddField(
            model_name='roots',
            name='rotter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_name', to='xlink.group'),
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('小学生', '小学生'), ('社会人', '社会人'), ('高校生', '高校生'), ('中学生', '中学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('PC', 'PC'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム'), ('TV', 'TV'), ('映画', '映画'), ('運動', '運動'), ('読書', '読書')], max_length=8),
        ),
        migrations.AlterField(
            model_name='roots',
            name='group',
            field=models.CharField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
