# Generated by Django 3.2.25 on 2024-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0007_auto_20240323_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='rooter_id',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('高校生', '高校生'), ('中学生', '中学生'), ('小学生', '小学生'), ('社会人', '社会人')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('読書', '読書'), ('映画', '映画'), ('TV', 'TV'), ('PC', 'PC'), ('プログラミング', 'プログラミング'), ('運動', '運動'), ('ゲーム', 'ゲーム')], max_length=8),
        ),
    ]
