# Generated by Django 3.2.25 on 2024-03-23 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xlink', '0008_auto_20240323_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('社会人', '社会人'), ('高校生', '高校生'), ('大学生', '大学生'), ('中学生', '中学生'), ('小学生', '小学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('プログラミング', 'プログラミング'), ('VR/AR', 'VR/AR'), ('TV', 'TV'), ('運動', '運動'), ('PC', 'PC'), ('読書', '読書'), ('ゲーム', 'ゲーム')], max_length=8),
        ),
        migrations.CreateModel(
            name='Rooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
