# Generated by Django 3.2.25 on 2024-03-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0010_auto_20240324_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='root',
            old_name='rooter',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('中学生', '中学生'), ('高校生', '高校生'), ('小学生', '小学生'), ('社会人', '社会人'), ('大学生', '大学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('TV', 'TV'), ('読書', '読書'), ('ゲーム', 'ゲーム'), ('PC', 'PC'), ('運動', '運動'), ('映画', '映画')], max_length=8),
        ),
    ]
