# Generated by Django 3.2.25 on 2024-03-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0011_auto_20240324_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='root',
            old_name='name',
            new_name='rooter',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('小学生', '小学生'), ('大学生', '大学生'), ('社会人', '社会人'), ('高校生', '高校生'), ('中学生', '中学生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('運動', '運動'), ('PC', 'PC'), ('ゲーム', 'ゲーム'), ('読書', '読書'), ('VR/AR', 'VR/AR'), ('プログラミング', 'プログラミング'), ('映画', '映画'), ('TV', 'TV')], max_length=8),
        ),
    ]
