# Generated by Django 3.2.25 on 2024-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0012_auto_20240324_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('小学生', '小学生'), ('社会人', '社会人'), ('中学生', '中学生'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('ゲーム', 'ゲーム'), ('VR/AR', 'VR/AR'), ('運動', '運動'), ('PC', 'PC'), ('読書', '読書'), ('映画', '映画'), ('TV', 'TV'), ('プログラミング', 'プログラミング')], max_length=8),
        ),
    ]
