# Generated by Django 3.2.25 on 2024-03-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0013_auto_20240324_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='user',
            field=models.CharField(default=1, max_length=10000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('社会人', '社会人'), ('小学生', '小学生'), ('中学生', '中学生'), ('大学生', '大学生'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('映画', '映画'), ('PC', 'PC'), ('VR/AR', 'VR/AR'), ('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('読書', '読書'), ('運動', '運動'), ('TV', 'TV')], max_length=8),
        ),
    ]
