# Generated by Django 3.2.25 on 2024-03-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0014_auto_20240324_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('高校生', '高校生'), ('大学生', '大学生'), ('中学生', '中学生'), ('小学生', '小学生'), ('社会人', '社会人')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('運動', '運動'), ('映画', '映画'), ('PC', 'PC'), ('TV', 'TV'), ('VR/AR', 'VR/AR'), ('読書', '読書'), ('プログラミング', 'プログラミング'), ('ゲーム', 'ゲーム')], max_length=8),
        ),
        migrations.AlterField(
            model_name='root',
            name='rooter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ルーター', to='xlink.group'),
        ),
    ]
