# Generated by Django 3.2.25 on 2024-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlink', '0018_auto_20240324_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='detail',
            field=models.CharField(choices=[('大学生', '大学生'), ('社会人', '社会人'), ('中学生', '中学生'), ('小学生', '小学生'), ('高校生', '高校生')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account',
            name='hobby',
            field=models.CharField(choices=[('VR/AR', 'VR/AR'), ('運動', '運動'), ('映画', '映画'), ('読書', '読書'), ('PC', 'PC'), ('ゲーム', 'ゲーム'), ('プログラミング', 'プログラミング'), ('TV', 'TV')], max_length=8),
        ),
    ]
